### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RomePx0516** [Matthew-Chandler/Micromouse-Weighted-Floodfill#1]
Hello there! I was wondering if it would be possible for the mouse to stop running back and forth in the maze after it has found the shortest path(final scan) and just settle in the goal cell? Would it require any major changes in the code? Thank you.

**Comment by matthew-chandler** [comment]
I just pushed an update to main that allows this. In ```constants.h```, set STAY_AT_CENTER to 1 and RESET_AT_CENTER to 0.
It changed a lot of the code, so you'll have to find some way to merge it with your current code if you made any changes.

It's been about a year since I coded this, and as of right now, it's quite unorganized. I'm planning on refactoring most of the code since I made this before I learned how to abstract well, so sorry about the mess. Please let me know if you have any other questions or if this broke anything!
